import { Feedback } from '@/lib/types/user';

export const mockFeedback: Feedback[] = [
  {
    id: '1',
    userId: 'user1',
    userName: 'Alex Johnson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    rating: 5,
    message: 'Excellent platform! The editor is smooth and the problems are well-curated.',
    type: 'general',
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '2',
    userId: 'user2',
    userName: 'Sarah Chen',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    rating: 4,
    message: 'Great learning experience. Would love to see more advanced problems.',
    type: 'feature',
    createdAt: new Date('2024-02-19'),
  },
  {
    id: '3',
    userId: 'user3',
    userName: 'Mike Davidson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike',
    rating: 5,
    message: 'The dark mode implementation is perfect. Love the UI/UX design.',
    type: 'general',
    createdAt: new Date('2024-02-18'),
  },
  {
    id: '4',
    userId: 'user4',
    userName: 'Emma Wilson',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    rating: 3,
    message: 'Found a bug with the code submission. Sometimes it hangs.',
    type: 'bug',
    createdAt: new Date('2024-02-17'),
  },
  {
    id: '5',
    userId: 'user5',
    userName: 'John Smith',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    rating: 5,
    message: 'Best DSA platform I\'ve used. The daily challenges keep me motivated!',
    type: 'general',
    createdAt: new Date('2024-02-16'),
  },
];
